# Generated by Django 4.1.6 on 2023-02-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='user',
            new_name='cour',
        ),
        migrations.AlterField(
            model_name='cour',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
