# Generated by Django 4.1.6 on 2023-02-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_user_part_cour_alter_cour_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='descreption',
            new_name='content',
        ),
    ]
